home:
  path: /
  controller: App\Controller\HomeController::index

homeCompetitions:
  path: /home/competitions
  controller: App\Controller\HomeController::competitions

competitionCreate:
  path: /competition/create
  controller: App\Controller\CompetitionController::createCompetition

competitionGet:
  path: /competition/get/{id}
  controller: App\Controller\CompetitionController::getCompetition
  methods:    [GET, HEAD]

organizerMain:
  path: /organizer/{hash}
  controller: App\Controller\OrganizerController::index

organizerCreateTeams:
  path: /organizer/{hash}/createTeams
  controller: App\Controller\OrganizerController::createTeam

oranizerDeleteTeam:
  path: /organizer/{hash}/deleteTeam/{idTeam}
  controller: App\Controller\OrganizerController::deleteTeam

organizerTeamsSectors:
  path: /organizer/{hash}/teamsSectors
  controller: App\Controller\OrganizerController::addSectors

organizerResults:
  path: /organizer/{hash}/results/{teamId}/{weighingNr}
  controller: App\Controller\OrganizerController::results

organizerFinishedCompetition:
  path: /organizer/{hash}/finish
  controller: App\Controller\OrganizerController::finish